from __future__ import annotations

from dataclasses import dataclass, field

from app.models import ApprovalStatus, SourceType


@dataclass(frozen=True, slots=True)
class SourceCatalogEntry:
    source_key: str
    display_name: str
    source_type: SourceType
    base_url: str
    canonical_hostname: str
    jurisdiction_scope: list[str]
    update_frequency: str
    access_method: str
    default_parser_version: str
    collector_type: str | None = None
    canonical_surfaces: list[str] = field(default_factory=list)
    mirror_surfaces: list[str] = field(default_factory=list)
    partition_scheme: str | None = None
    expected_proof_type: str | None = None
    auth_mode: str | None = None
    critical: bool = True
    metadata_profile: dict[str, object] = field(default_factory=dict)
    approval_status: ApprovalStatus = ApprovalStatus.APPROVED
    notes: str | None = None


SOURCE_CATALOG: dict[str, SourceCatalogEntry] = {
    "constitution_of_india": SourceCatalogEntry(
        source_key="constitution_of_india",
        display_name="Constitution of India Corpus",
        source_type=SourceType.STATUTE_PORTAL,
        base_url="https://www.indiacode.nic.in",
        canonical_hostname="www.indiacode.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="ad hoc",
        access_method="structured_text",
        default_parser_version="constitution-text-v1",
        notes="Canonical constitutional text and amendments.",
    ),
    "india_code": SourceCatalogEntry(
        source_key="india_code",
        display_name="India Code Central Acts",
        source_type=SourceType.STATUTE_PORTAL,
        base_url="https://www.indiacode.nic.in",
        canonical_hostname="www.indiacode.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="structured_text",
        default_parser_version="indiacode-text-v1",
        notes="Central bare acts and section text.",
    ),
    "bns_bundle": SourceCatalogEntry(
        source_key="bns_bundle",
        display_name="BNS / BNSS / BSA Corpus",
        source_type=SourceType.STATUTE_PORTAL,
        base_url="https://www.indiacode.nic.in",
        canonical_hostname="www.indiacode.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="ad hoc",
        access_method="structured_text",
        default_parser_version="criminal-code-text-v1",
        notes="New criminal codes effective July 1, 2024.",
    ),
    "supreme_court": SourceCatalogEntry(
        source_key="supreme_court",
        display_name="Supreme Court of India",
        source_type=SourceType.COURT_PORTAL,
        base_url="https://www.sci.gov.in",
        canonical_hostname="www.sci.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="ajax_captcha_search",
        default_parser_version="supreme-court-sci-free-text-v1",
        collector_type="ajax_captcha_search",
        canonical_surfaces=[
            "https://www.sci.gov.in/free-text-judgements/",
            "https://www.sci.gov.in/judgements-case-no/",
            "https://api.sci.gov.in/supremecourt/*",
        ],
        mirror_surfaces=[
            "https://api.sci.gov.in/judis",
            "https://verdictfinder.sci.gov.in/elk_frontend/",
        ],
        partition_scheme="query_term_x_date_window_x_page",
        expected_proof_type="window_page_closure",
        auth_mode="captcha_public",
        critical=True,
        metadata_profile={
            "required": [
                "source_url",
                "source_document_ref",
                "collector_run_id",
                "parser_version",
                "checksum",
                "doc_type",
                "title",
                "date_text",
            ]
        },
        notes="Use official SCI AJAX judgment surfaces first; AWS bulk is only a partial backfill and not sufficient for the full target.",
    ),
    "bombay_high_court": SourceCatalogEntry(
        source_key="bombay_high_court",
        display_name="Bombay High Court",
        source_type=SourceType.COURT_PORTAL,
        base_url="https://bombayhighcourt.nic.in",
        canonical_hostname="bombayhighcourt.nic.in",
        jurisdiction_scope=["Maharashtra", "Goa"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="high-court-html-v1",
    ),
    "delhi_high_court": SourceCatalogEntry(
        source_key="delhi_high_court",
        display_name="Delhi High Court",
        source_type=SourceType.COURT_PORTAL,
        base_url="https://delhihighcourt.nic.in",
        canonical_hostname="delhihighcourt.nic.in",
        jurisdiction_scope=["Delhi"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="high-court-html-v1",
    ),
    "madras_high_court": SourceCatalogEntry(
        source_key="madras_high_court",
        display_name="Madras High Court",
        source_type=SourceType.COURT_PORTAL,
        base_url="https://www.mhc.tn.gov.in",
        canonical_hostname="www.mhc.tn.gov.in",
        jurisdiction_scope=["Tamil Nadu", "Puducherry"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="high-court-html-v1",
    ),
    "nclt": SourceCatalogEntry(
        source_key="nclt",
        display_name="National Company Law Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://nclt.gov.in",
        canonical_hostname="nclt.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="weekly",
        access_method="html_parser",
        default_parser_version="tribunal-html-v1",
    ),
    "itat": SourceCatalogEntry(
        source_key="itat",
        display_name="Income Tax Appellate Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://itat.gov.in",
        canonical_hostname="itat.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="archive_post_listing",
        default_parser_version="itat-archives-v1",
        collector_type="archive_post_listing",
        canonical_surfaces=[
            "https://itat.gov.in/home/archives",
            "https://itat.gov.in/judicial/tribunalorders",
        ],
        mirror_surfaces=["https://itat.gov.in/public/files/upload/*"],
        partition_scheme="archives_page_name_date_window",
        expected_proof_type="archive_window_closure",
        auth_mode="public",
        critical=True,
        metadata_profile={
            "required": [
                "source_url",
                "source_document_ref",
                "collector_run_id",
                "parser_version",
                "checksum",
                "doc_type",
                "title",
                "date_text",
            ]
        },
        notes="Tax tribunal corpus via official archives POST listing plus tribunal order search.",
    ),
    "cestat": SourceCatalogEntry(
        source_key="cestat",
        display_name="Customs, Excise and Service Tax Appellate Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://cestat.gov.in",
        canonical_hostname="cestat.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="direct_document_enumerator",
        default_parser_version="cestat-openfile-v1",
        collector_type="direct_document_enumerator",
        canonical_surfaces=[
            "https://cestat.gov.in/openfile/2/*",
            "https://cestat.gov.in/final-order-status-all",
        ],
        mirror_surfaces=["https://www.cis.cestat.gov.in"],
        partition_scheme="openfile_kind_2_numeric_id",
        expected_proof_type="numeric_range_closure",
        auth_mode="public",
        critical=True,
        metadata_profile={
            "required": [
                "source_url",
                "source_document_ref",
                "collector_run_id",
                "parser_version",
                "checksum",
                "doc_type",
            ]
        },
        notes="Primary alternate official route is the sparse numeric /openfile/2/<id> document surface.",
    ),
    "aft": SourceCatalogEntry(
        source_key="aft",
        display_name="Armed Forces Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://www.aftdelhi.nic.in",
        canonical_hostname="www.aftdelhi.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="aft-pdf-seed-v1",
        collector_type="direct_pdf_listing_and_html_seed",
        canonical_surfaces=[
            "https://www.aftdelhi.nic.in/index.php?Itemid=67&id=30&option=com_content&view=article",
            "https://www.aftdelhi.nic.in/index.php/judgement/reportable-judgements",
            "https://www.aftdelhi.nic.in/index.php/judgement/large-bench-orders",
        ],
        mirror_surfaces=[
            "https://aftrbghy.nic.in/judgements.asp",
            "https://aftjaipur.gov.in/judgement/date",
            "https://aftlko.up.nic.in/JUDGMENTS.html",
        ],
        partition_scheme="seed_surface_x_crawl",
        expected_proof_type="seed_surface_closure",
        auth_mode="public",
        critical=True,
        metadata_profile={
            "required": [
                "source_url",
                "source_document_ref",
                "collector_run_id",
                "parser_version",
                "checksum",
                "doc_type",
            ]
        },
        notes="Use the Delhi article index plus regional bench judgment pages because they expose direct official PDFs.",
    ),
    "ngt": SourceCatalogEntry(
        source_key="ngt",
        display_name="National Green Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://greentribunal.gov.in",
        canonical_hostname="greentribunal.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="tribunal-html-v1",
        notes="Environmental tribunal orders and related statutory directions.",
    ),
    "nclat": SourceCatalogEntry(
        source_key="nclat",
        display_name="National Company Law Appellate Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://nclat.nic.in",
        canonical_hostname="nclat.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="weekly",
        access_method="html_parser",
        default_parser_version="tribunal-html-v1",
        notes="Company law appellate tribunal orders, cause lists, and notices.",
    ),
    "cat": SourceCatalogEntry(
        source_key="cat",
        display_name="Central Administrative Tribunal",
        source_type=SourceType.TRIBUNAL_PORTAL,
        base_url="https://cgat.gov.in",
        canonical_hostname="cgat.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="weekly",
        access_method="api_or_html",
        default_parser_version="tribunal-html-v1",
        notes="CAT orders/judgments exposed via SPA/API; may require special access parameters.",
    ),
    "rbi": SourceCatalogEntry(
        source_key="rbi",
        display_name="Reserve Bank of India",
        source_type=SourceType.API,
        base_url="https://www.rbi.org.in",
        canonical_hostname="www.rbi.org.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="rbi-pdf-v1",
        notes="RBI notifications, circulars, press releases (PDF attachments).",
    ),
    "sebi": SourceCatalogEntry(
        source_key="sebi",
        display_name="Securities and Exchange Board of India",
        source_type=SourceType.API,
        base_url="https://www.sebi.gov.in",
        canonical_hostname="www.sebi.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="sebi-pdf-v1",
        notes="SEBI circulars, orders, and press releases (PDF attachments).",
    ),
    "cbic": SourceCatalogEntry(
        source_key="cbic",
        display_name="Central Board of Indirect Taxes and Customs",
        source_type=SourceType.API,
        base_url="https://cbic-gst.gov.in",
        canonical_hostname="cbic-gst.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="cbic-gst-sitemap-v1",
        notes="CBIC circulars/notifications/instructions (seeded from cbic-gst.gov.in sitemap for stability).",
    ),
    "cbdt": SourceCatalogEntry(
        source_key="cbdt",
        display_name="Central Board of Direct Taxes",
        source_type=SourceType.API,
        base_url="https://www.incometaxindia.gov.in",
        canonical_hostname="www.incometaxindia.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="api_or_html",
        default_parser_version="cbdt-circulars-v1",
        notes="CBDT circulars and related tax updates exposed via incometaxindia.gov.in APIs.",
    ),
    "ecourts_district_history": SourceCatalogEntry(
        source_key="ecourts_district_history",
        display_name="eCourts District History",
        source_type=SourceType.API,
        base_url="https://services.ecourts.gov.in",
        canonical_hostname="services.ecourts.gov.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="api_or_html",
        default_parser_version="ecourts-history-v1",
        notes="District and subordinate procedural history keyed by CNR.",
    ),
    "gazette_legal_change": SourceCatalogEntry(
        source_key="gazette_legal_change",
        display_name="Gazette Legal Change Feed",
        source_type=SourceType.STATUTE_PORTAL,
        base_url="https://egazette.nic.in",
        canonical_hostname="egazette.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="daily",
        access_method="html_parser",
        default_parser_version="gazette-change-v1",
        notes="Commencement, repeal, substitution, and notification change layer.",
    ),
    "law_commission_reports": SourceCatalogEntry(
        source_key="law_commission_reports",
        display_name="Law Commission of India Reports",
        source_type=SourceType.REPORTS_PORTAL,
        base_url="https://lawcommissionofindia.nic.in",
        canonical_hostname="lawcommissionofindia.nic.in",
        jurisdiction_scope=["All India"],
        update_frequency="ad hoc",
        access_method="pdf_text",
        default_parser_version="law-commission-report-text-v1",
        notes="Law Commission reports and supplemental notes (PDF-derived plain text).",
    ),
}
